version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.alpine
    steps:
      - checkout
      - run: pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7-alpine
    steps:
      - checkout
      - run: python test/test_book.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
